# Generated by Django 4.1 on 2023-11-23 17:15

from django.db import migrations, models
import recipe_finder_api.OptionalPicturesRecipe.Model.ModelOptionPictures


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_finder_api', '0008_optionpicturesrecipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optionpicturesrecipe',
            name='link',
        ),
        migrations.AddField(
            model_name='optionpicturesrecipe',
            name='picture',
            field=models.ImageField(default='not_image.png', upload_to=recipe_finder_api.OptionalPicturesRecipe.Model.ModelOptionPictures.namePicture),
        ),
    ]
